[package]
name = "my_status"
version = "1.0.0"
authors = ["Robbe Van Herck <robbe@robbevanherck.be>"]
edition = '2021'

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
battery = "0.7.8"
